//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlutterCinemaAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class DatVe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatVe()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int MaDat { get; set; }
        public Nullable<int> MaPhim { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string Ghe { get; set; }
        public Nullable<double> GiaTien { get; set; }
        public Nullable<System.DateTime> ThoiGianDat { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Phim Phim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
