//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlutterCinemaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string MaHoaDon { get; set; }
        public string MaKH { get; set; }
        public string MaPhim { get; set; }
        public string MaVe { get; set; }
        public string MaDoAn { get; set; }
        public Nullable<double> TongTien { get; set; }
    
        public virtual DoAn DoAn { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual LoaiVe LoaiVe { get; set; }
        public virtual Phim Phim { get; set; }
    }
}
