//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlutterCinemaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHD { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaDat { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> ThoiGianTT { get; set; }
    
        public virtual DatVe DatVe { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
